### ISSUE TITLE
Make a check for NaN positions 

### ISSUE THREAD

**Issue by P4sca1** [Kefta/Ragdoll-Remover#10]
Maybe this will prevent some more server crashes (like in my case).

**Comment by Kefta** [comment]
The game automatically removes nan ragdolls, but they can still cause crashes before it can; I don't know if a lua script would make any difference

**Comment by P4sca1** [comment]
Could you give me a script, I want to try this. Maybe it can help :3

code_gs <notifications@github.com> schrieb am Sa., 15. Aug. 2015 um
17:18 Uhr:

**Comment by Kefta** [comment]
Fixed
