### ISSUE TITLE
Error Plagues Console

### ISSUE THREAD

**Issue by FlashyCorgi** [Kefta/Ragdoll-Remover#12]
L 10/22/2015 - 06:11:01: Lua Error: 
[ERROR] lua/autorun/server/gs_ragdollremover.lua:90: attempt to call method 'GetRole' (a nil value)
  1. IdentifyCorpse - lua/autorun/server/gs_ragdollremover.lua:90
   2. fn - lua/autorun/server/gs_ragdollremover.lua:155
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

I have the file located in /garrysmod/lua/autorun/server/gs_ragdollremover.lua. I also made a customization by removing the IF CLIENT THEN RETURN END because since it is in the server folder, I didn't think it needs it. If this would cause the error, let me know. Otherwise, do you know what would cause this?

It appears to happen when no one is on the server and just spams the console. Yet, it is not exclusive to that, it appears players were on  during this time, but it still gave the error.

**Comment by Kefta** [comment]
Are you running TTT?

**Comment by FlashyCorgi** [comment]
Yessir, and it is in the folder, so I do not need to set TTT to true.

**Comment by Kefta** [comment]
Added a workaround; this seems more like a TTT bug, however
