### ISSUE TITLE
Serverside

### ISSUE THREAD

**Issue by deinemudda32** [Kefta/Ragdoll-Remover#8]
This is serverside, so run it serverside ^^

**Comment by Kefta** [comment]
Are you getting some kind of errors? I run it shared because of the TTT body functions

**Comment by deinemudda32** [comment]
No I run this serverside. Works well. No problems at all.

**Comment by Kefta** [comment]
And how does this benefit over running it shared?

**Comment by deinemudda32** [comment]
1. It cant be stolen.
2. It dont run via the client also.

**Comment by Kefta** [comment]
Why would I care if it got stolen?
